// ═══════════════════════════════════════════════════════════════
// Contractor & Associate onboarding — task generation engine
//
// Design: the Resourcing Lead creates a record by answering a small set of
// inputs (who, when, who owns it, what's required). NAYA derives the full
// task list from those inputs — the contractor/associate never configures
// their own onboarding, and the creator never hand-builds a checklist.
// This file is the single source of truth for that derivation, used by both
// the creation API and the dashboard/contractor-facing views.
//
// `engagement_type` distinguishes Contractor from Associate on top of the
// SAME engine — there is deliberately no second task engine. Everything
// else (phases, dependencies, readiness) is shared.
// ═══════════════════════════════════════════════════════════════

export type TaskOwner = 'resourcing' | 'project' | 'delivery' | 'contractor' | 'it_client_admin' | 'legal_compliance';
export type TaskStatus =
  | 'NOT_STARTED'
  | 'IN_PROGRESS'
  | 'WAITING_ON_CONTRACTOR'
  | 'WAITING_ON_INTERNAL'
  | 'WAITING_ON_CLIENT'
  | 'COMPLETE'
  | 'NOT_APPLICABLE'
  | 'BLOCKED';
export type TaskPhase = 'clearance' | 'access' | 'kickoff' | 'billing';
export type EngagementType = 'contractor' | 'associate';

// Georgie's four-value classification — descriptive metadata on each task,
// not a second status field. "Core" = always generated. "Conditional" =
// generated when the matching requirement is Yes or Unsure. "Custom" =
// reserved for a future hand-added task (not generated by this engine
// today). "Not applicable" = a conditional task whose requirement was
// answered No, so it was never generated at all.
export type TaskClassification = 'core' | 'conditional' | 'custom';

export type TaskHistoryEntry = {
  previous_status: TaskStatus | null;
  new_status: TaskStatus;
  updated_by: string; // 'admin' | 'contractor' — single shared admin role until real per-person identity exists
  updated_at: number;
  note?: string;
};

export type TaskResource = { label: string; url: string } | null;

export type ContractorTask = {
  id: string;
  phase: TaskPhase;
  title: string;
  why_it_matters: string;
  owner: TaskOwner;
  classification: TaskClassification;
  conditional: boolean; // kept for backward compatibility with existing records/UI — equivalent to classification !== 'core'
  status: TaskStatus;
  depends_on: string[]; // task ids that must be COMPLETE or NOT_APPLICABLE before this one can be COMPLETE
  due_date: string | null;
  notes: string;
  blocked_reason: string | null;
  history: TaskHistoryEntry[];
  resource: TaskResource; // null renders as "Resource to be confirmed" — never a fabricated link
  contact_for_help: string; // free text, e.g. a role name — '' if not set
  blocks_readiness: boolean; // almost always true; false only for a requirement explicitly marked as not blocking (e.g. client access that "can follow induction")
};

export type RequirementAnswer = 'yes' | 'no' | 'unsure';
export type VerificationMethod = 'hours' | 'deliverables';
export type BillingCadence = 'weekly' | 'monthly' | 'milestone';
export type AccessPolicy = 'required_before_start' | 'can_follow_induction';

export type ContractorRequirements = {
  // Contract & compliance
  nda: RequirementAnswer;
  background_check: RequirementAnswer; // "Background or compliance review"
  insurance: RequirementAnswer;
  hr_legal_review: RequirementAnswer;
  // Systems & access
  niit_account: RequirementAnswer;
  hardware: RequirementAnswer;
  client_access: RequirementAnswer;
  client_access_policy: AccessPolicy; // only meaningful when client_access is yes/unsure — NAYA never invents this, the admin sets it
  client_badge: RequirementAnswer;
  // Induction & training (NIIT training + CAS induction are core, not asked here)
  client_training: RequirementAnswer;
  client_training_policy: AccessPolicy;
  project_training: RequirementAnswer;
  // Time & billing
  time_tracking: RequirementAnswer;
  invoicing: RequirementAnswer;
  // Deferred to a later task by default — not asked at creation.
  verification_method: VerificationMethod | null;
  billing_cadence: BillingCadence | null;
};

export type ContractorRecord = {
  journey_type: 'contractor';
  engagement_type: EngagementType;
  country_of_work: string;
  invite_token_hash?: string; // one-way lookup key only — never the raw token, which is shown once at issue/regenerate and never persisted
  invite_expires_at?: number;
  contractor_id: string;
  contractor_name: string;
  contractor_email: string;
  project_name: string;
  client: string; // free text, or 'Internal / no external client'
  start_date: string; // ISO date (yyyy-mm-dd)
  end_date: string; // '' unless the engagement is fixed-term
  resourcing_lead: string;
  project_lead: string; // '' until confirmed — moved to a later task if not known at creation
  delivery_manager: string; // '' until set — moved to a later task
  requirements: ContractorRequirements;
  tasks: ContractorTask[];
  created_at: number;
  last_saved: number;
};

export const PHASE_LABELS: Record<TaskPhase, string> = {
  clearance: 'Contract & Compliance',
  access: 'Systems & Access',
  kickoff: 'Project Integration & Induction',
  billing: 'Time & Billing',
};
export const PHASE_ORDER: TaskPhase[] = ['clearance', 'access', 'kickoff', 'billing'];

export const OWNER_LABELS: Record<TaskOwner, string> = {
  resourcing: 'Resourcing Lead',
  project: 'Project Lead',
  delivery: 'Delivery Manager',
  contractor: 'Contractor',
  it_client_admin: 'IT / Client Admin',
  legal_compliance: 'Legal / Compliance',
};

export const STATUS_LABELS: Record<TaskStatus, string> = {
  NOT_STARTED: 'Not started',
  IN_PROGRESS: 'In progress',
  WAITING_ON_CONTRACTOR: 'Waiting on contractor',
  WAITING_ON_INTERNAL: 'Waiting on internal team',
  WAITING_ON_CLIENT: 'Waiting on client',
  COMPLETE: 'Complete',
  NOT_APPLICABLE: 'Not applicable',
  BLOCKED: 'Blocked',
};

export const CLASSIFICATION_LABELS: Record<TaskClassification, string> = {
  core: 'Core',
  conditional: 'Conditional',
  custom: 'Custom',
};

function makeTask(
  id: string, phase: TaskPhase, title: string, why_it_matters: string, owner: TaskOwner,
  classification: TaskClassification, opts?: { resource?: TaskResource; contact_for_help?: string; blocks_readiness?: boolean },
): ContractorTask {
  return {
    id, phase, title, why_it_matters, owner,
    classification, conditional: classification !== 'core',
    status: 'NOT_STARTED',
    depends_on: [],
    due_date: null,
    notes: '',
    blocked_reason: null,
    history: [],
    resource: opts?.resource ?? null,
    contact_for_help: opts?.contact_for_help ?? '',
    blocks_readiness: opts?.blocks_readiness ?? true,
  };
}

const RESOURCES = {
  niitTraining: { label: 'NIIT Mandatory Training Hub', url: 'https://learning.niit.com/mandatory-training' } as TaskResource,
  casInduction: { label: 'CAS Induction Pack', url: 'https://cas.niit.com/induction' } as TaskResource,
};
// Per the brief: never fabricate a resource that hasn't been validated.
// Anything not explicitly confirmed stays null -> "Resource to be confirmed".
const UNCONFIRMED: TaskResource = null;

// ── Core tasks — always generated regardless of requirements ──
export function generateCoreTasks(opts?: { projectLeadKnown?: boolean }): ContractorTask[] {
  const tasks: ContractorTask[] = [];

  tasks.push(makeTask('C1', 'clearance', 'Confirm engagement / SOW', 'The engagement agreement is the legal basis for everything that follows — nothing else can be relied on until it\'s signed.', 'resourcing', 'core'));

  if (!opts?.projectLeadKnown) {
    tasks.push(makeTask('K0', 'kickoff', 'Assign or confirm Project Lead', 'The Project Lead owns day-to-day direction — kickoff can\'t be scheduled meaningfully without one.', 'resourcing', 'core'));
  }
  tasks.push(makeTask('K1', 'kickoff', 'Schedule project kickoff', 'Kickoff is where the working relationship actually starts — it should happen as close to day one as possible.', 'project', 'core'));
  tasks.push(makeTask('K2', 'kickoff', 'Explain project scope and ways of working', 'Avoids early misunderstandings about what\'s in scope and how the team actually works day to day.', 'project', 'core'));
  tasks.push(makeTask('K3', 'kickoff', 'Assign initial project tasks', 'Gives the person real work to start on immediately after kickoff, rather than a gap at the start.', 'project', 'core'));

  tasks.push(makeTask('T1', 'kickoff', 'Complete applicable NIIT mandatory training', 'NIIT requires baseline training for anyone working under its name, regardless of engagement type.', 'contractor', 'core', { resource: RESOURCES.niitTraining }));
  tasks.push(makeTask('T2', 'kickoff', 'Complete CAS induction', 'CAS induction covers how this specific practice operates — not covered by general NIIT training.', 'contractor', 'core', { resource: RESOURCES.casInduction }));

  tasks.push(makeTask('K4', 'kickoff', 'Confirm key contacts', 'Makes sure the person knows who to go to for access issues, project questions, and billing — before they need to ask.', 'resourcing', 'core'));
  tasks.push(makeTask('B0', 'billing', 'Confirm missing billing information (verification method, billing cadence, Delivery Manager)', 'These details are rarely known at engagement creation — this is where they get captured instead of blocking the record.', 'resourcing', 'core'));
  tasks.push(makeTask('R1', 'billing', 'Confirm readiness', 'The final checkpoint before the engagement is marked Ready to start — a deliberate human confirmation, not just the computed gates.', 'resourcing', 'core'));

  return tasks;
}

// Only added when the matching requirement is Yes (the real task) or Unsure
// (a confirmation task — never silently dropped). Never asked about
// individually beyond the Step 2 answers.
export function generateConditionalTasks(req: ContractorRequirements): ContractorTask[] {
  const tasks: ContractorTask[] = [];

  const add = (
    answer: RequirementAnswer, realId: string, phase: TaskPhase, realTitle: string, why: string, owner: TaskOwner,
    opts?: { resource?: TaskResource; blocks_readiness?: boolean; confirmBlocksReadiness?: boolean },
  ) => {
    if (answer === 'yes') {
      tasks.push(makeTask(realId, phase, realTitle, why, owner, 'conditional', { resource: opts?.resource, blocks_readiness: opts?.blocks_readiness }));
    } else if (answer === 'unsure') {
      tasks.push(makeTask(`${realId}_CONF`, phase, `Confirm requirement: ${realTitle}`, 'This was left as "to be confirmed" at creation — NAYA never assumes it away, so it stays open until someone resolves it.', 'resourcing', 'conditional', { blocks_readiness: opts?.confirmBlocksReadiness ?? opts?.blocks_readiness ?? true }));
    }
  };

  // Contract & Compliance
  if (req.nda === 'yes') {
    tasks.push(makeTask('C2', 'clearance', 'Send NDA', 'An NDA protects both sides before any confidential project information is shared.', 'resourcing', 'conditional'));
    tasks.push(makeTask('C3', 'clearance', 'Sign NDA', 'The contractor\'s own signature is what makes the NDA enforceable.', 'contractor', 'conditional'));
  } else if (req.nda === 'unsure') {
    tasks.push(makeTask('C2_CONF', 'clearance', 'Confirm requirement: NDA', 'Left as "to be confirmed" — NAYA never assumes it away.', 'resourcing', 'conditional'));
  }
  add(req.background_check, 'CC1', 'clearance', 'Complete background / compliance check', 'Required before the person can be given any real access or responsibility on the engagement.', 'legal_compliance');
  add(req.insurance, 'INS1', 'clearance', 'Provide insurance evidence', 'Confirms the contractor carries the cover the engagement requires before work begins.', 'contractor');
  add(req.hr_legal_review, 'HRL1', 'clearance', 'HR / Legal classification review', 'Confirms the engagement is classified and structured correctly before it proceeds.', 'legal_compliance');

  // Systems & Access
  add(req.niit_account, 'A1', 'access', 'Create NIIT email / account', 'Needed before almost anything else — most other systems key off this account.', 'resourcing', { blocks_readiness: true });
  add(req.hardware, 'HW1', 'access', 'Arrange NIIT hardware', 'The person can\'t do NIIT-side work without NIIT-issued equipment.', 'it_client_admin', { blocks_readiness: true });
  add(req.client_access, 'CA1', 'access', 'Request client system access', 'Needed to actually work in the client\'s environment.', 'it_client_admin', {
    blocks_readiness: req.client_access_policy !== 'can_follow_induction',
    confirmBlocksReadiness: req.client_access_policy !== 'can_follow_induction',
  });
  add(req.client_badge, 'CB1', 'access', 'Arrange client badge / physical access', 'Needed for any on-site presence at the client.', 'it_client_admin');

  // Induction & Training (NIIT training / CAS induction are core — see generateCoreTasks)
  add(req.client_training, 'CT1', 'kickoff', 'Complete client-required training', 'Some clients require their own training before anyone can start on their systems or site.', 'contractor', {
    resource: UNCONFIRMED,
    blocks_readiness: req.client_training_policy !== 'can_follow_induction',
    confirmBlocksReadiness: req.client_training_policy !== 'can_follow_induction',
  });
  add(req.project_training, 'PT1', 'kickoff', 'Complete project-specific training', 'Covers tools or processes specific to this project that general induction doesn\'t.', 'contractor', { resource: UNCONFIRMED });

  // Time & Billing
  if (req.time_tracking === 'yes') {
    tasks.push(makeTask('TT1', 'billing', 'Set up time-tracking codes', 'Required before any time can be logged correctly.', 'resourcing', 'conditional'));
    tasks.push(makeTask('TT2', 'billing', 'Brief contractor on time entry', 'Avoids incorrectly logged time in the first week.', 'resourcing', 'conditional'));
  } else if (req.time_tracking === 'unsure') {
    tasks.push(makeTask('TT1_CONF', 'billing', 'Confirm requirement: Time tracking', 'Left as "to be confirmed" — NAYA never assumes it away.', 'resourcing', 'conditional'));
  }
  add(req.invoicing, 'INV1', 'billing', 'Confirm invoicing process', 'Needed before the first invoice can be submitted correctly.', 'delivery');

  return tasks;
}

// Only the dependencies the spec actually calls for — not a blanket
// "depends on the whole previous phase." Applied by id, so it's a no-op for
// any task that wasn't generated (an excluded requirement never creates a
// task, so it can never appear as a dependency either).
function assignDependencies(tasks: ContractorTask[]): ContractorTask[] {
  const byId = new Map(tasks.map(t => [t.id, t]));
  const has = (id: string) => byId.has(id);
  const setDeps = (id: string, deps: string[]) => {
    const t = byId.get(id);
    if (t) t.depends_on = deps.filter(has);
  };

  // Systems/access tasks depend on the agreement being confirmed.
  ['A1', 'HW1', 'CA1', 'CB1'].forEach(id => setDeps(id, ['C1']));

  // Project kickoff depends on the Project Lead being confirmed (only
  // meaningful if K0 exists — otherwise the Lead was already known).
  if (has('K0')) setDeps('K1', ['K0']);

  // Initial task assignment depends on kickoff having happened.
  setDeps('K3', ['K1']);

  // First time-entry readiness depends on time-tracking setup.
  if (has('TT1')) setDeps('TT2', ['TT1']);

  // Readiness confirmation depends on training/induction and billing basics.
  setDeps('R1', ['T1', 'T2', 'B0'].filter(has));

  return tasks;
}

export function generateContractorTasks(req: ContractorRequirements, opts?: { projectLeadKnown?: boolean }): ContractorTask[] {
  const all = [...generateCoreTasks(opts), ...generateConditionalTasks(req)];
  return assignDependencies(all);
}

export function countCoreTasks(opts?: { projectLeadKnown?: boolean }): number {
  return generateCoreTasks(opts).length;
}

export function countConditionalTasks(req: ContractorRequirements): number {
  return generateConditionalTasks(req).length;
}

export function taskProgress(tasks: ContractorTask[]): { done: number; total: number; pct: number } {
  const applicable = tasks.filter(t => t.status !== 'NOT_APPLICABLE');
  const done = applicable.filter(t => t.status === 'COMPLETE').length;
  const total = applicable.length || 1;
  return { done, total, pct: Math.round((done / total) * 100) };
}

// A phase "clears" when every applicable, readiness-blocking task in it is
// COMPLETE. An empty/all-N/A/non-blocking phase counts as cleared. This is
// also what makes excluded requirements harmless for readiness: a task that
// was never generated simply isn't part of any phase's gate, and a task
// explicitly marked non-blocking (e.g. client access that "can follow
// induction") is tracked but doesn't hold up readiness.
export function phaseGate(tasks: ContractorTask[], phase: TaskPhase): boolean {
  const applicable = tasks.filter(t => t.phase === phase && t.status !== 'NOT_APPLICABLE' && t.blocks_readiness !== false);
  return applicable.every(t => t.status === 'COMPLETE');
}

export function readinessGates(tasks: ContractorTask[]): Record<TaskPhase, boolean> {
  return {
    clearance: phaseGate(tasks, 'clearance'),
    access: phaseGate(tasks, 'access'),
    kickoff: phaseGate(tasks, 'kickoff'),
    billing: phaseGate(tasks, 'billing'),
  };
}

// Computed, never stored, never manually ticked — always derived fresh from
// the four gates so it can't drift from the underlying task states.
export function isReadyToStart(tasks: ContractorTask[]): boolean {
  const g = readinessGates(tasks);
  return g.clearance && g.access && g.kickoff && g.billing;
}

// A task can move to COMPLETE only once everything it depends on is COMPLETE
// or NOT_APPLICABLE. Returns the blocking task titles, if any.
export function blockingDependencies(tasks: ContractorTask[], task: ContractorTask): ContractorTask[] {
  if (!task.depends_on.length) return [];
  const byId = new Map(tasks.map(t => [t.id, t]));
  return task.depends_on
    .map(id => byId.get(id))
    .filter((t): t is ContractorTask => !!t && t.status !== 'COMPLETE' && t.status !== 'NOT_APPLICABLE');
}

// Defensive server-side check — the task graph is always engine-generated
// today, never user-editable, but this guards against a future change (or a
// hand-crafted API request) introducing a dependency on a task that doesn't
// exist, or a dependency cycle that would make a task permanently
// uncompletable.
export function validateTaskGraph(tasks: ContractorTask[]): string | null {
  const ids = new Set(tasks.map(t => t.id));
  for (const t of tasks) {
    for (const dep of t.depends_on) {
      if (!ids.has(dep)) return `Task "${t.id}" depends on unknown task "${dep}"`;
    }
  }
  const WHITE = 0, GRAY = 1, BLACK = 2;
  const color = new Map<string, number>();
  const byId = new Map(tasks.map(t => [t.id, t]));
  const visit = (id: string): string | null => {
    color.set(id, GRAY);
    const task = byId.get(id);
    for (const dep of task?.depends_on || []) {
      const c = color.get(dep) ?? WHITE;
      if (c === GRAY) return `Circular dependency involving "${id}" and "${dep}"`;
      if (c === WHITE) {
        const err = visit(dep);
        if (err) return err;
      }
    }
    color.set(id, BLACK);
    return null;
  };
  for (const id of Array.from(ids)) {
    if ((color.get(id) ?? WHITE) === WHITE) {
      const err = visit(id);
      if (err) return err;
    }
  }
  return null;
}

export function defaultRequirements(): ContractorRequirements {
  return {
    nda: 'yes', background_check: 'no', insurance: 'no', hr_legal_review: 'no',
    niit_account: 'yes', hardware: 'no', client_access: 'no', client_access_policy: 'required_before_start',
    client_badge: 'no',
    client_training: 'no', client_training_policy: 'required_before_start', project_training: 'no',
    time_tracking: 'yes', invoicing: 'yes',
    verification_method: null, billing_cadence: null,
  };
}

// Brings an older record (earlier status values, boolean requirements, a
// missing engagement_type, missing task fields) up to the current display
// shape. Applied in-memory wherever a record is read — never a bulk job
// against KV. A record is only re-persisted in this shape the next time
// something on it is actually updated, and its EXISTING tasks are never
// regenerated or altered here — only normalized so every field the UI
// expects is present.
export function migrateContractorRecord(record: any): ContractorRecord {
  const STATUS_MAP: Record<string, TaskStatus> = { PENDING: 'NOT_STARTED' };
  const tasks: ContractorTask[] = (record.tasks || [])
    // The old "Ready to start — final sign-off" task is obsolete now that
    // readiness is computed — drop it from view rather than leave a dead
    // manually-clickable task sitting in the billing phase.
    .filter((t: any) => !(t.id === 'B5' && /ready to start/i.test(t.title || '')))
    .map((t: any) => ({
      id: t.id,
      phase: t.phase,
      title: t.title,
      why_it_matters: t.why_it_matters || '',
      owner: t.owner,
      classification: t.classification || (t.conditional ? 'conditional' : 'core'),
      conditional: !!t.conditional,
      status: STATUS_MAP[t.status] || t.status || 'NOT_STARTED',
      depends_on: Array.isArray(t.depends_on) ? t.depends_on : [],
      due_date: t.due_date ?? null,
      notes: t.notes ?? '',
      blocked_reason: t.blocked_reason ?? null,
      history: Array.isArray(t.history) ? t.history : [],
      resource: t.resource ?? null,
      contact_for_help: t.contact_for_help ?? '',
      blocks_readiness: t.blocks_readiness !== false,
    }));
  const r = record.requirements || {};
  const toAnswer = (legacyBool: any, current: any): RequirementAnswer =>
    current === 'yes' || current === 'no' || current === 'unsure' ? current : (legacyBool ? 'yes' : 'no');
  return {
    journey_type: 'contractor',
    engagement_type: record.engagement_type === 'associate' ? 'associate' : 'contractor',
    country_of_work: record.country_of_work || '',
    invite_token_hash: record.invite_token_hash,
    invite_expires_at: record.invite_expires_at,
    contractor_id: record.contractor_id,
    contractor_name: record.contractor_name,
    contractor_email: record.contractor_email,
    project_name: record.project_name,
    client: record.client,
    start_date: record.start_date || '',
    end_date: record.end_date || '',
    resourcing_lead: record.resourcing_lead || '',
    project_lead: record.project_lead || '',
    delivery_manager: record.delivery_manager || '',
    requirements: {
      nda: toAnswer(r.nda, r.nda),
      background_check: toAnswer(r.client_compliance, r.background_check),
      insurance: toAnswer(r.insurance, r.insurance),
      hr_legal_review: toAnswer(false, r.hr_legal_review),
      niit_account: toAnswer(r.niit_account, r.niit_account),
      hardware: toAnswer(r.hardware, r.hardware),
      client_access: toAnswer(r.client_access, r.client_access),
      client_access_policy: r.client_access_policy === 'can_follow_induction' ? 'can_follow_induction' : 'required_before_start',
      client_badge: toAnswer(r.client_badge, r.client_badge),
      client_training: toAnswer(false, r.client_training),
      client_training_policy: r.client_training_policy === 'can_follow_induction' ? 'can_follow_induction' : 'required_before_start',
      project_training: toAnswer(false, r.project_training),
      time_tracking: toAnswer(r.time_tracking, r.time_tracking),
      invoicing: toAnswer(r.invoicing, r.invoicing),
      verification_method: r.verification_method ?? null,
      billing_cadence: r.billing_cadence ?? null,
    },
    tasks,
    created_at: record.created_at || record.last_saved || Date.now(),
    last_saved: record.last_saved || Date.now(),
  };
}
